<?xml version="1.0" encoding="utf-8"?><Database Name="Valvoline" Class="ValvolineDBDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=43.252.91.100;Initial Catalog=Valvoline;User ID=docopd" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="Atoot_BandhanConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Customers" Member="Customers">
    <Type Name="Customer">
      <Column Name="CustomerId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Country" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.del_tblcity_master" Member="del_tblcity_masters">
    <Type Name="del_tblcity_master">
      <Column Name="city_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="state_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="city_name" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="status" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.del_tbldistrict" Member="del_tbldistricts">
    <Type Name="del_tbldistrict">
      <Column Name="district_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="city_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="district_name" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="status" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.del_tblstate" Member="del_tblstates">
    <Type Name="del_tblstate">
      <Column Name="state_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="state_name" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="status" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.['Pincode List$']" Member="_Pincode_List__s">
    <Type Name="_Pincode_List__">
      <Column Name="id" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="state" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="city" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="district" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="pincode" Type="System.Double" DbType="Float" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tblcampaign" Member="tblcampaigns">
    <Type Name="tblcampaign">
      <Column Name="campaign_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="client_name" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="campaign_name" Type="System.String" DbType="NVarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="start_date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="end_date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="status" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="StateName" Type="System.String" DbType="NVarChar(40)" CanBeNull="true" />
      <Column Name="District" Type="System.String" DbType="NVarChar(40)" CanBeNull="true" />
      <Column Name="TeamId" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Association Name="tblcampaign_tbllocation" Member="tbllocations" ThisKey="campaign_id" OtherKey="campaign_id" Type="tbllocation" />
      <Association Name="tblcampaign_tbluser" Member="tblusers" ThisKey="campaign_id" OtherKey="campaign_id" Type="tbluser" />
    </Type>
  </Table>
  <Table Name="dbo.tblduplicate_valvoline_data" Member="tblduplicate_valvoline_datas">
    <Type Name="tblduplicate_valvoline_data">
      <Column Name="id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name_of_person" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="name_of_outlet" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="contact_number" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="image_url" Type="System.String" DbType="VarChar(300)" CanBeNull="true" />
      <Column Name="pincode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="adhar_number" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="workshop" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="segment" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="counter_potential" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="no_of_services" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="valvoline_usage" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="preferred_retailer" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="remarks" Type="System.String" DbType="VarChar(300)" CanBeNull="true" />
      <Column Name="street_location" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="state" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="city" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="district" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="campaign_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="team_name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="lat" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="[log]" Member="log" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="otp_password" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="otp_verification" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="mob_verify_status" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="organization_source" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="authenticated_contact" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="authenticated_by" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="near_by_location" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="record_input_form" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="createdOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="imei_no" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="deleted_on" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="date_of_birth" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="source_of_contact" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="UserId" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbllocations" Member="tbllocations">
    <Type Name="tbllocation">
      <Column Name="location_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="user_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="campaign_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="team_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="state" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="district" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="tblcampaign_tbllocation" Member="tblcampaign" ThisKey="campaign_id" OtherKey="campaign_id" Type="tblcampaign" IsForeignKey="true" DeleteRule="CASCADE" />
      <Association Name="tblteam_tbllocation" Member="tblteam" ThisKey="team_id" OtherKey="team_id" Type="tblteam" IsForeignKey="true" DeleteRule="CASCADE" />
    </Type>
  </Table>
  <Table Name="dbo.tblpincode" Member="tblpincodes">
    <Type Name="tblpincode">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="state" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="city" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="district" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="pincode" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tblsegment" Member="tblsegments">
    <Type Name="tblsegment">
      <Column Name="[sno.]" Member="sno_" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="segment" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tblteam" Member="tblteams">
    <Type Name="tblteam">
      <Column Name="team_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="team_name" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="password" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="user_type" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="state" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="District" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="tblteam_tbllocation" Member="tbllocations" ThisKey="team_id" OtherKey="team_id" Type="tbllocation" />
      <Association Name="tblteam_tbluser" Member="tblusers" ThisKey="team_id" OtherKey="team_id" Type="tbluser" />
    </Type>
  </Table>
  <Table Name="dbo.tbluser" Member="tblusers">
    <Type Name="tbluser">
      <Column Name="user_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="team_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="campaign_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="location_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="user_name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="imei_first" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="imei_second" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="status" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="createdOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="state" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="District" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MobileNo" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="Roles" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="EmailId" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Association Name="tblcampaign_tbluser" Member="tblcampaign" ThisKey="campaign_id" OtherKey="campaign_id" Type="tblcampaign" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="tblteam_tbluser" Member="tblteam" ThisKey="team_id" OtherKey="team_id" Type="tblteam" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tblUserSegment" Member="tblUserSegments">
    <Type Name="tblUserSegment">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Segment" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CreatedOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="IsDeleted" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tblUserState" Member="tblUserStates">
    <Type Name="tblUserState">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="State" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CreatedOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="IsDeleted" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tblworkshops" Member="tblworkshops">
    <Type Name="tblworkshop">
      <Column Name="[sno.]" Member="sno_" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="workshop" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tempLoc" Member="tempLocs">
    <Type Name="tempLoc">
      <Column Name="Name" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Latitude" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Longitude" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tblOTPStatus" Member="tblOTPStatus">
    <Type Name="tblOTPStatus">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TagId" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MobileNumber" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Message" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CreatedOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Isdeleted" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tblvalvoline_detail" Member="tblvalvoline_details">
    <Type Name="tblvalvoline_detail">
      <Column Name="id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name_of_person" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="name_of_outlet" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="contact_number" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="image_url" Type="System.String" DbType="VarChar(300)" CanBeNull="true" />
      <Column Name="pincode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="adhar_number" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="workshop" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="segment" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="counter_potential" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="no_of_services" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="valvoline_usage" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="preferred_retailer" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="remarks" Type="System.String" DbType="VarChar(300)" CanBeNull="true" />
      <Column Name="street_location" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="state" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="city" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="district" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="campaign_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="team_name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="lat" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="[log]" Member="log" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="otp_password" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="otp_verification" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="mob_verify_status" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="organization_source" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="authenticated_contact" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="authenticated_by" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="near_by_location" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="record_input_form" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="createdOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="imei_no" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="deleted_on" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="is_verfy" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="update_count" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="source_of_contact" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="date_of_birth" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="UserId" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="UpdateOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
</Database>