#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Valvoline")]
public partial class ValvolineDBDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  partial void Insertdel_tblcity_master(del_tblcity_master instance);
  partial void Updatedel_tblcity_master(del_tblcity_master instance);
  partial void Deletedel_tblcity_master(del_tblcity_master instance);
  partial void Inserttblcampaign(tblcampaign instance);
  partial void Updatetblcampaign(tblcampaign instance);
  partial void Deletetblcampaign(tblcampaign instance);
  partial void Inserttbllocation(tbllocation instance);
  partial void Updatetbllocation(tbllocation instance);
  partial void Deletetbllocation(tbllocation instance);
  partial void Inserttblpincode(tblpincode instance);
  partial void Updatetblpincode(tblpincode instance);
  partial void Deletetblpincode(tblpincode instance);
  partial void Inserttblteam(tblteam instance);
  partial void Updatetblteam(tblteam instance);
  partial void Deletetblteam(tblteam instance);
  partial void Inserttbluser(tbluser instance);
  partial void Updatetbluser(tbluser instance);
  partial void Deletetbluser(tbluser instance);
  partial void InserttblUserSegment(tblUserSegment instance);
  partial void UpdatetblUserSegment(tblUserSegment instance);
  partial void DeletetblUserSegment(tblUserSegment instance);
  partial void InserttblUserState(tblUserState instance);
  partial void UpdatetblUserState(tblUserState instance);
  partial void DeletetblUserState(tblUserState instance);
  partial void InserttblOTPStatus(tblOTPStatus instance);
  partial void UpdatetblOTPStatus(tblOTPStatus instance);
  partial void DeletetblOTPStatus(tblOTPStatus instance);
  partial void Inserttblvalvoline_detail(tblvalvoline_detail instance);
  partial void Updatetblvalvoline_detail(tblvalvoline_detail instance);
  partial void Deletetblvalvoline_detail(tblvalvoline_detail instance);
  #endregion
	
	public ValvolineDBDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["Atoot_BandhanConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public ValvolineDBDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public ValvolineDBDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public ValvolineDBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public ValvolineDBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<Customer> Customers
	{
		get
		{
			return this.GetTable<Customer>();
		}
	}
	
	public System.Data.Linq.Table<del_tblcity_master> del_tblcity_masters
	{
		get
		{
			return this.GetTable<del_tblcity_master>();
		}
	}
	
	public System.Data.Linq.Table<del_tbldistrict> del_tbldistricts
	{
		get
		{
			return this.GetTable<del_tbldistrict>();
		}
	}
	
	public System.Data.Linq.Table<del_tblstate> del_tblstates
	{
		get
		{
			return this.GetTable<del_tblstate>();
		}
	}
	
	public System.Data.Linq.Table<_Pincode_List__> _Pincode_List__s
	{
		get
		{
			return this.GetTable<_Pincode_List__>();
		}
	}
	
	public System.Data.Linq.Table<tblcampaign> tblcampaigns
	{
		get
		{
			return this.GetTable<tblcampaign>();
		}
	}
	
	public System.Data.Linq.Table<tblduplicate_valvoline_data> tblduplicate_valvoline_datas
	{
		get
		{
			return this.GetTable<tblduplicate_valvoline_data>();
		}
	}
	
	public System.Data.Linq.Table<tbllocation> tbllocations
	{
		get
		{
			return this.GetTable<tbllocation>();
		}
	}
	
	public System.Data.Linq.Table<tblpincode> tblpincodes
	{
		get
		{
			return this.GetTable<tblpincode>();
		}
	}
	
	public System.Data.Linq.Table<tblsegment> tblsegments
	{
		get
		{
			return this.GetTable<tblsegment>();
		}
	}
	
	public System.Data.Linq.Table<tblteam> tblteams
	{
		get
		{
			return this.GetTable<tblteam>();
		}
	}
	
	public System.Data.Linq.Table<tbluser> tblusers
	{
		get
		{
			return this.GetTable<tbluser>();
		}
	}
	
	public System.Data.Linq.Table<tblUserSegment> tblUserSegments
	{
		get
		{
			return this.GetTable<tblUserSegment>();
		}
	}
	
	public System.Data.Linq.Table<tblUserState> tblUserStates
	{
		get
		{
			return this.GetTable<tblUserState>();
		}
	}
	
	public System.Data.Linq.Table<tblworkshop> tblworkshops
	{
		get
		{
			return this.GetTable<tblworkshop>();
		}
	}
	
	public System.Data.Linq.Table<tempLoc> tempLocs
	{
		get
		{
			return this.GetTable<tempLoc>();
		}
	}
	
	public System.Data.Linq.Table<tblOTPStatus> tblOTPStatus
	{
		get
		{
			return this.GetTable<tblOTPStatus>();
		}
	}
	
	public System.Data.Linq.Table<tblvalvoline_detail> tblvalvoline_details
	{
		get
		{
			return this.GetTable<tblvalvoline_detail>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Customers")]
public partial class Customer
{
	
	private int _CustomerId;
	
	private string _Name;
	
	private string _Country;
	
	public Customer()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustomerId", DbType="Int NOT NULL")]
	public int CustomerId
	{
		get
		{
			return this._CustomerId;
		}
		set
		{
			if ((this._CustomerId != value))
			{
				this._CustomerId = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
	public string Name
	{
		get
		{
			return this._Name;
		}
		set
		{
			if ((this._Name != value))
			{
				this._Name = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Country", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string Country
	{
		get
		{
			return this._Country;
		}
		set
		{
			if ((this._Country != value))
			{
				this._Country = value;
			}
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.del_tblcity_master")]
public partial class del_tblcity_master : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _city_id;
	
	private System.Nullable<int> _state_id;
	
	private string _city_name;
	
	private bool _status;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Oncity_idChanging(int value);
    partial void Oncity_idChanged();
    partial void Onstate_idChanging(System.Nullable<int> value);
    partial void Onstate_idChanged();
    partial void Oncity_nameChanging(string value);
    partial void Oncity_nameChanged();
    partial void OnstatusChanging(bool value);
    partial void OnstatusChanged();
    #endregion
	
	public del_tblcity_master()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_city_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int city_id
	{
		get
		{
			return this._city_id;
		}
		set
		{
			if ((this._city_id != value))
			{
				this.Oncity_idChanging(value);
				this.SendPropertyChanging();
				this._city_id = value;
				this.SendPropertyChanged("city_id");
				this.Oncity_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_state_id", DbType="Int")]
	public System.Nullable<int> state_id
	{
		get
		{
			return this._state_id;
		}
		set
		{
			if ((this._state_id != value))
			{
				this.Onstate_idChanging(value);
				this.SendPropertyChanging();
				this._state_id = value;
				this.SendPropertyChanged("state_id");
				this.Onstate_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_city_name", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
	public string city_name
	{
		get
		{
			return this._city_name;
		}
		set
		{
			if ((this._city_name != value))
			{
				this.Oncity_nameChanging(value);
				this.SendPropertyChanging();
				this._city_name = value;
				this.SendPropertyChanged("city_name");
				this.Oncity_nameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status", DbType="Bit NOT NULL")]
	public bool status
	{
		get
		{
			return this._status;
		}
		set
		{
			if ((this._status != value))
			{
				this.OnstatusChanging(value);
				this.SendPropertyChanging();
				this._status = value;
				this.SendPropertyChanged("status");
				this.OnstatusChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.del_tbldistrict")]
public partial class del_tbldistrict
{
	
	private int _district_id;
	
	private System.Nullable<int> _city_id;
	
	private string _district_name;
	
	private bool _status;
	
	public del_tbldistrict()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_district_id", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
	public int district_id
	{
		get
		{
			return this._district_id;
		}
		set
		{
			if ((this._district_id != value))
			{
				this._district_id = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_city_id", DbType="Int")]
	public System.Nullable<int> city_id
	{
		get
		{
			return this._city_id;
		}
		set
		{
			if ((this._city_id != value))
			{
				this._city_id = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_district_name", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
	public string district_name
	{
		get
		{
			return this._district_name;
		}
		set
		{
			if ((this._district_name != value))
			{
				this._district_name = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status", DbType="Bit NOT NULL")]
	public bool status
	{
		get
		{
			return this._status;
		}
		set
		{
			if ((this._status != value))
			{
				this._status = value;
			}
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.del_tblstate")]
public partial class del_tblstate
{
	
	private int _state_id;
	
	private string _state_name;
	
	private bool _status;
	
	public del_tblstate()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_state_id", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
	public int state_id
	{
		get
		{
			return this._state_id;
		}
		set
		{
			if ((this._state_id != value))
			{
				this._state_id = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_state_name", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
	public string state_name
	{
		get
		{
			return this._state_name;
		}
		set
		{
			if ((this._state_name != value))
			{
				this._state_name = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status", DbType="Bit NOT NULL")]
	public bool status
	{
		get
		{
			return this._status;
		}
		set
		{
			if ((this._status != value))
			{
				this._status = value;
			}
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[\'Pincode List$\']")]
public partial class _Pincode_List__
{
	
	private string _id;
	
	private string _state;
	
	private string _city;
	
	private string _district;
	
	private System.Nullable<double> _pincode;
	
	public _Pincode_List__()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="NVarChar(255)")]
	public string id
	{
		get
		{
			return this._id;
		}
		set
		{
			if ((this._id != value))
			{
				this._id = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_state", DbType="NVarChar(255)")]
	public string state
	{
		get
		{
			return this._state;
		}
		set
		{
			if ((this._state != value))
			{
				this._state = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_city", DbType="NVarChar(255)")]
	public string city
	{
		get
		{
			return this._city;
		}
		set
		{
			if ((this._city != value))
			{
				this._city = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_district", DbType="NVarChar(255)")]
	public string district
	{
		get
		{
			return this._district;
		}
		set
		{
			if ((this._district != value))
			{
				this._district = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pincode", DbType="Float")]
	public System.Nullable<double> pincode
	{
		get
		{
			return this._pincode;
		}
		set
		{
			if ((this._pincode != value))
			{
				this._pincode = value;
			}
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblcampaign")]
public partial class tblcampaign : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _campaign_id;
	
	private string _client_name;
	
	private string _campaign_name;
	
	private System.DateTime _start_date;
	
	private System.DateTime _end_date;
	
	private System.Nullable<bool> _status;
	
	private string _StateName;
	
	private string _District;
	
	private string _TeamId;
	
	private EntitySet<tbllocation> _tbllocations;
	
	private EntitySet<tbluser> _tblusers;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Oncampaign_idChanging(int value);
    partial void Oncampaign_idChanged();
    partial void Onclient_nameChanging(string value);
    partial void Onclient_nameChanged();
    partial void Oncampaign_nameChanging(string value);
    partial void Oncampaign_nameChanged();
    partial void Onstart_dateChanging(System.DateTime value);
    partial void Onstart_dateChanged();
    partial void Onend_dateChanging(System.DateTime value);
    partial void Onend_dateChanged();
    partial void OnstatusChanging(System.Nullable<bool> value);
    partial void OnstatusChanged();
    partial void OnStateNameChanging(string value);
    partial void OnStateNameChanged();
    partial void OnDistrictChanging(string value);
    partial void OnDistrictChanged();
    partial void OnTeamIdChanging(string value);
    partial void OnTeamIdChanged();
    #endregion
	
	public tblcampaign()
	{
		this._tbllocations = new EntitySet<tbllocation>(new Action<tbllocation>(this.attach_tbllocations), new Action<tbllocation>(this.detach_tbllocations));
		this._tblusers = new EntitySet<tbluser>(new Action<tbluser>(this.attach_tblusers), new Action<tbluser>(this.detach_tblusers));
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_campaign_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int campaign_id
	{
		get
		{
			return this._campaign_id;
		}
		set
		{
			if ((this._campaign_id != value))
			{
				this.Oncampaign_idChanging(value);
				this.SendPropertyChanging();
				this._campaign_id = value;
				this.SendPropertyChanged("campaign_id");
				this.Oncampaign_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_client_name", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
	public string client_name
	{
		get
		{
			return this._client_name;
		}
		set
		{
			if ((this._client_name != value))
			{
				this.Onclient_nameChanging(value);
				this.SendPropertyChanging();
				this._client_name = value;
				this.SendPropertyChanged("client_name");
				this.Onclient_nameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_campaign_name", DbType="NVarChar(40) NOT NULL", CanBeNull=false)]
	public string campaign_name
	{
		get
		{
			return this._campaign_name;
		}
		set
		{
			if ((this._campaign_name != value))
			{
				this.Oncampaign_nameChanging(value);
				this.SendPropertyChanging();
				this._campaign_name = value;
				this.SendPropertyChanged("campaign_name");
				this.Oncampaign_nameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_start_date", DbType="DateTime NOT NULL")]
	public System.DateTime start_date
	{
		get
		{
			return this._start_date;
		}
		set
		{
			if ((this._start_date != value))
			{
				this.Onstart_dateChanging(value);
				this.SendPropertyChanging();
				this._start_date = value;
				this.SendPropertyChanged("start_date");
				this.Onstart_dateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_end_date", DbType="DateTime NOT NULL")]
	public System.DateTime end_date
	{
		get
		{
			return this._end_date;
		}
		set
		{
			if ((this._end_date != value))
			{
				this.Onend_dateChanging(value);
				this.SendPropertyChanging();
				this._end_date = value;
				this.SendPropertyChanged("end_date");
				this.Onend_dateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status", DbType="Bit")]
	public System.Nullable<bool> status
	{
		get
		{
			return this._status;
		}
		set
		{
			if ((this._status != value))
			{
				this.OnstatusChanging(value);
				this.SendPropertyChanging();
				this._status = value;
				this.SendPropertyChanged("status");
				this.OnstatusChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StateName", DbType="NVarChar(40)")]
	public string StateName
	{
		get
		{
			return this._StateName;
		}
		set
		{
			if ((this._StateName != value))
			{
				this.OnStateNameChanging(value);
				this.SendPropertyChanging();
				this._StateName = value;
				this.SendPropertyChanged("StateName");
				this.OnStateNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_District", DbType="NVarChar(40)")]
	public string District
	{
		get
		{
			return this._District;
		}
		set
		{
			if ((this._District != value))
			{
				this.OnDistrictChanging(value);
				this.SendPropertyChanging();
				this._District = value;
				this.SendPropertyChanged("District");
				this.OnDistrictChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TeamId", DbType="NVarChar(30)")]
	public string TeamId
	{
		get
		{
			return this._TeamId;
		}
		set
		{
			if ((this._TeamId != value))
			{
				this.OnTeamIdChanging(value);
				this.SendPropertyChanging();
				this._TeamId = value;
				this.SendPropertyChanged("TeamId");
				this.OnTeamIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblcampaign_tbllocation", Storage="_tbllocations", ThisKey="campaign_id", OtherKey="campaign_id")]
	public EntitySet<tbllocation> tbllocations
	{
		get
		{
			return this._tbllocations;
		}
		set
		{
			this._tbllocations.Assign(value);
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblcampaign_tbluser", Storage="_tblusers", ThisKey="campaign_id", OtherKey="campaign_id")]
	public EntitySet<tbluser> tblusers
	{
		get
		{
			return this._tblusers;
		}
		set
		{
			this._tblusers.Assign(value);
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void attach_tbllocations(tbllocation entity)
	{
		this.SendPropertyChanging();
		entity.tblcampaign = this;
	}
	
	private void detach_tbllocations(tbllocation entity)
	{
		this.SendPropertyChanging();
		entity.tblcampaign = null;
	}
	
	private void attach_tblusers(tbluser entity)
	{
		this.SendPropertyChanging();
		entity.tblcampaign = this;
	}
	
	private void detach_tblusers(tbluser entity)
	{
		this.SendPropertyChanging();
		entity.tblcampaign = null;
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblduplicate_valvoline_data")]
public partial class tblduplicate_valvoline_data
{
	
	private long _id;
	
	private string _name_of_person;
	
	private string _name_of_outlet;
	
	private System.Nullable<long> _contact_number;
	
	private string _image_url;
	
	private System.Nullable<int> _pincode;
	
	private System.Nullable<long> _adhar_number;
	
	private string _workshop;
	
	private string _segment;
	
	private System.Nullable<long> _counter_potential;
	
	private System.Nullable<long> _no_of_services;
	
	private System.Nullable<long> _valvoline_usage;
	
	private string _preferred_retailer;
	
	private string _remarks;
	
	private string _street_location;
	
	private string _state;
	
	private string _city;
	
	private string _district;
	
	private System.Nullable<int> _campaign_id;
	
	private string _team_name;
	
	private string _lat;
	
	private string _log;
	
	private string _otp_password;
	
	private System.Nullable<bool> _otp_verification;
	
	private System.Nullable<bool> _mob_verify_status;
	
	private string _organization_source;
	
	private string _authenticated_contact;
	
	private string _authenticated_by;
	
	private string _near_by_location;
	
	private string _record_input_form;
	
	private System.Nullable<System.DateTime> _createdOn;
	
	private string _imei_no;
	
	private System.Nullable<bool> _deleted_on;
	
	private string _date_of_birth;
	
	private string _source_of_contact;
	
	private string _UserId;
	
	public tblduplicate_valvoline_data()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.Always, DbType="BigInt NOT NULL IDENTITY", IsDbGenerated=true)]
	public long id
	{
		get
		{
			return this._id;
		}
		set
		{
			if ((this._id != value))
			{
				this._id = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name_of_person", DbType="VarChar(100)")]
	public string name_of_person
	{
		get
		{
			return this._name_of_person;
		}
		set
		{
			if ((this._name_of_person != value))
			{
				this._name_of_person = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name_of_outlet", DbType="VarChar(100)")]
	public string name_of_outlet
	{
		get
		{
			return this._name_of_outlet;
		}
		set
		{
			if ((this._name_of_outlet != value))
			{
				this._name_of_outlet = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_contact_number", DbType="BigInt")]
	public System.Nullable<long> contact_number
	{
		get
		{
			return this._contact_number;
		}
		set
		{
			if ((this._contact_number != value))
			{
				this._contact_number = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_image_url", DbType="VarChar(300)")]
	public string image_url
	{
		get
		{
			return this._image_url;
		}
		set
		{
			if ((this._image_url != value))
			{
				this._image_url = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pincode", DbType="Int")]
	public System.Nullable<int> pincode
	{
		get
		{
			return this._pincode;
		}
		set
		{
			if ((this._pincode != value))
			{
				this._pincode = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_adhar_number", DbType="BigInt")]
	public System.Nullable<long> adhar_number
	{
		get
		{
			return this._adhar_number;
		}
		set
		{
			if ((this._adhar_number != value))
			{
				this._adhar_number = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_workshop", DbType="VarChar(50)")]
	public string workshop
	{
		get
		{
			return this._workshop;
		}
		set
		{
			if ((this._workshop != value))
			{
				this._workshop = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_segment", DbType="VarChar(50)")]
	public string segment
	{
		get
		{
			return this._segment;
		}
		set
		{
			if ((this._segment != value))
			{
				this._segment = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_counter_potential", DbType="BigInt")]
	public System.Nullable<long> counter_potential
	{
		get
		{
			return this._counter_potential;
		}
		set
		{
			if ((this._counter_potential != value))
			{
				this._counter_potential = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_no_of_services", DbType="BigInt")]
	public System.Nullable<long> no_of_services
	{
		get
		{
			return this._no_of_services;
		}
		set
		{
			if ((this._no_of_services != value))
			{
				this._no_of_services = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_valvoline_usage", DbType="BigInt")]
	public System.Nullable<long> valvoline_usage
	{
		get
		{
			return this._valvoline_usage;
		}
		set
		{
			if ((this._valvoline_usage != value))
			{
				this._valvoline_usage = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_preferred_retailer", DbType="VarChar(100)")]
	public string preferred_retailer
	{
		get
		{
			return this._preferred_retailer;
		}
		set
		{
			if ((this._preferred_retailer != value))
			{
				this._preferred_retailer = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_remarks", DbType="VarChar(300)")]
	public string remarks
	{
		get
		{
			return this._remarks;
		}
		set
		{
			if ((this._remarks != value))
			{
				this._remarks = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_street_location", DbType="VarChar(100)")]
	public string street_location
	{
		get
		{
			return this._street_location;
		}
		set
		{
			if ((this._street_location != value))
			{
				this._street_location = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_state", DbType="VarChar(50)")]
	public string state
	{
		get
		{
			return this._state;
		}
		set
		{
			if ((this._state != value))
			{
				this._state = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_city", DbType="VarChar(50)")]
	public string city
	{
		get
		{
			return this._city;
		}
		set
		{
			if ((this._city != value))
			{
				this._city = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_district", DbType="VarChar(50)")]
	public string district
	{
		get
		{
			return this._district;
		}
		set
		{
			if ((this._district != value))
			{
				this._district = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_campaign_id", DbType="Int")]
	public System.Nullable<int> campaign_id
	{
		get
		{
			return this._campaign_id;
		}
		set
		{
			if ((this._campaign_id != value))
			{
				this._campaign_id = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_team_name", DbType="VarChar(50)")]
	public string team_name
	{
		get
		{
			return this._team_name;
		}
		set
		{
			if ((this._team_name != value))
			{
				this._team_name = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lat", DbType="VarChar(50)")]
	public string lat
	{
		get
		{
			return this._lat;
		}
		set
		{
			if ((this._lat != value))
			{
				this._lat = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[log]", Storage="_log", DbType="VarChar(50)")]
	public string log
	{
		get
		{
			return this._log;
		}
		set
		{
			if ((this._log != value))
			{
				this._log = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_otp_password", DbType="VarChar(10)")]
	public string otp_password
	{
		get
		{
			return this._otp_password;
		}
		set
		{
			if ((this._otp_password != value))
			{
				this._otp_password = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_otp_verification", DbType="Bit")]
	public System.Nullable<bool> otp_verification
	{
		get
		{
			return this._otp_verification;
		}
		set
		{
			if ((this._otp_verification != value))
			{
				this._otp_verification = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mob_verify_status", DbType="Bit")]
	public System.Nullable<bool> mob_verify_status
	{
		get
		{
			return this._mob_verify_status;
		}
		set
		{
			if ((this._mob_verify_status != value))
			{
				this._mob_verify_status = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_organization_source", DbType="VarChar(50)")]
	public string organization_source
	{
		get
		{
			return this._organization_source;
		}
		set
		{
			if ((this._organization_source != value))
			{
				this._organization_source = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_authenticated_contact", DbType="VarChar(50)")]
	public string authenticated_contact
	{
		get
		{
			return this._authenticated_contact;
		}
		set
		{
			if ((this._authenticated_contact != value))
			{
				this._authenticated_contact = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_authenticated_by", DbType="VarChar(50)")]
	public string authenticated_by
	{
		get
		{
			return this._authenticated_by;
		}
		set
		{
			if ((this._authenticated_by != value))
			{
				this._authenticated_by = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_near_by_location", DbType="VarChar(100)")]
	public string near_by_location
	{
		get
		{
			return this._near_by_location;
		}
		set
		{
			if ((this._near_by_location != value))
			{
				this._near_by_location = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_record_input_form", DbType="VarChar(MAX)")]
	public string record_input_form
	{
		get
		{
			return this._record_input_form;
		}
		set
		{
			if ((this._record_input_form != value))
			{
				this._record_input_form = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_createdOn", DbType="DateTime")]
	public System.Nullable<System.DateTime> createdOn
	{
		get
		{
			return this._createdOn;
		}
		set
		{
			if ((this._createdOn != value))
			{
				this._createdOn = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_imei_no", DbType="NVarChar(50)")]
	public string imei_no
	{
		get
		{
			return this._imei_no;
		}
		set
		{
			if ((this._imei_no != value))
			{
				this._imei_no = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_deleted_on", DbType="Bit")]
	public System.Nullable<bool> deleted_on
	{
		get
		{
			return this._deleted_on;
		}
		set
		{
			if ((this._deleted_on != value))
			{
				this._deleted_on = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_date_of_birth", DbType="VarChar(50)")]
	public string date_of_birth
	{
		get
		{
			return this._date_of_birth;
		}
		set
		{
			if ((this._date_of_birth != value))
			{
				this._date_of_birth = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_source_of_contact", DbType="VarChar(50)")]
	public string source_of_contact
	{
		get
		{
			return this._source_of_contact;
		}
		set
		{
			if ((this._source_of_contact != value))
			{
				this._source_of_contact = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserId", DbType="NVarChar(30)")]
	public string UserId
	{
		get
		{
			return this._UserId;
		}
		set
		{
			if ((this._UserId != value))
			{
				this._UserId = value;
			}
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbllocations")]
public partial class tbllocation : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _location_id;
	
	private System.Nullable<int> _user_id;
	
	private System.Nullable<int> _campaign_id;
	
	private System.Nullable<int> _team_id;
	
	private string _state;
	
	private string _district;
	
	private EntityRef<tblcampaign> _tblcampaign;
	
	private EntityRef<tblteam> _tblteam;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onlocation_idChanging(int value);
    partial void Onlocation_idChanged();
    partial void Onuser_idChanging(System.Nullable<int> value);
    partial void Onuser_idChanged();
    partial void Oncampaign_idChanging(System.Nullable<int> value);
    partial void Oncampaign_idChanged();
    partial void Onteam_idChanging(System.Nullable<int> value);
    partial void Onteam_idChanged();
    partial void OnstateChanging(string value);
    partial void OnstateChanged();
    partial void OndistrictChanging(string value);
    partial void OndistrictChanged();
    #endregion
	
	public tbllocation()
	{
		this._tblcampaign = default(EntityRef<tblcampaign>);
		this._tblteam = default(EntityRef<tblteam>);
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_location_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int location_id
	{
		get
		{
			return this._location_id;
		}
		set
		{
			if ((this._location_id != value))
			{
				this.Onlocation_idChanging(value);
				this.SendPropertyChanging();
				this._location_id = value;
				this.SendPropertyChanged("location_id");
				this.Onlocation_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_id", DbType="Int")]
	public System.Nullable<int> user_id
	{
		get
		{
			return this._user_id;
		}
		set
		{
			if ((this._user_id != value))
			{
				this.Onuser_idChanging(value);
				this.SendPropertyChanging();
				this._user_id = value;
				this.SendPropertyChanged("user_id");
				this.Onuser_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_campaign_id", DbType="Int")]
	public System.Nullable<int> campaign_id
	{
		get
		{
			return this._campaign_id;
		}
		set
		{
			if ((this._campaign_id != value))
			{
				if (this._tblcampaign.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.Oncampaign_idChanging(value);
				this.SendPropertyChanging();
				this._campaign_id = value;
				this.SendPropertyChanged("campaign_id");
				this.Oncampaign_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_team_id", DbType="Int")]
	public System.Nullable<int> team_id
	{
		get
		{
			return this._team_id;
		}
		set
		{
			if ((this._team_id != value))
			{
				if (this._tblteam.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.Onteam_idChanging(value);
				this.SendPropertyChanging();
				this._team_id = value;
				this.SendPropertyChanged("team_id");
				this.Onteam_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_state", DbType="VarChar(50)")]
	public string state
	{
		get
		{
			return this._state;
		}
		set
		{
			if ((this._state != value))
			{
				this.OnstateChanging(value);
				this.SendPropertyChanging();
				this._state = value;
				this.SendPropertyChanged("state");
				this.OnstateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_district", DbType="VarChar(50)")]
	public string district
	{
		get
		{
			return this._district;
		}
		set
		{
			if ((this._district != value))
			{
				this.OndistrictChanging(value);
				this.SendPropertyChanging();
				this._district = value;
				this.SendPropertyChanged("district");
				this.OndistrictChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblcampaign_tbllocation", Storage="_tblcampaign", ThisKey="campaign_id", OtherKey="campaign_id", IsForeignKey=true, DeleteRule="CASCADE")]
	public tblcampaign tblcampaign
	{
		get
		{
			return this._tblcampaign.Entity;
		}
		set
		{
			tblcampaign previousValue = this._tblcampaign.Entity;
			if (((previousValue != value) 
						|| (this._tblcampaign.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._tblcampaign.Entity = null;
					previousValue.tbllocations.Remove(this);
				}
				this._tblcampaign.Entity = value;
				if ((value != null))
				{
					value.tbllocations.Add(this);
					this._campaign_id = value.campaign_id;
				}
				else
				{
					this._campaign_id = default(Nullable<int>);
				}
				this.SendPropertyChanged("tblcampaign");
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblteam_tbllocation", Storage="_tblteam", ThisKey="team_id", OtherKey="team_id", IsForeignKey=true, DeleteRule="CASCADE")]
	public tblteam tblteam
	{
		get
		{
			return this._tblteam.Entity;
		}
		set
		{
			tblteam previousValue = this._tblteam.Entity;
			if (((previousValue != value) 
						|| (this._tblteam.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._tblteam.Entity = null;
					previousValue.tbllocations.Remove(this);
				}
				this._tblteam.Entity = value;
				if ((value != null))
				{
					value.tbllocations.Add(this);
					this._team_id = value.team_id;
				}
				else
				{
					this._team_id = default(Nullable<int>);
				}
				this.SendPropertyChanged("tblteam");
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblpincode")]
public partial class tblpincode : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _id;
	
	private string _state;
	
	private string _city;
	
	private string _district;
	
	private string _pincode;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnstateChanging(string value);
    partial void OnstateChanged();
    partial void OncityChanging(string value);
    partial void OncityChanged();
    partial void OndistrictChanging(string value);
    partial void OndistrictChanged();
    partial void OnpincodeChanging(string value);
    partial void OnpincodeChanged();
    #endregion
	
	public tblpincode()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int id
	{
		get
		{
			return this._id;
		}
		set
		{
			if ((this._id != value))
			{
				this.OnidChanging(value);
				this.SendPropertyChanging();
				this._id = value;
				this.SendPropertyChanged("id");
				this.OnidChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_state", DbType="VarChar(50)")]
	public string state
	{
		get
		{
			return this._state;
		}
		set
		{
			if ((this._state != value))
			{
				this.OnstateChanging(value);
				this.SendPropertyChanging();
				this._state = value;
				this.SendPropertyChanged("state");
				this.OnstateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_city", DbType="VarChar(50)")]
	public string city
	{
		get
		{
			return this._city;
		}
		set
		{
			if ((this._city != value))
			{
				this.OncityChanging(value);
				this.SendPropertyChanging();
				this._city = value;
				this.SendPropertyChanged("city");
				this.OncityChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_district", DbType="VarChar(50)")]
	public string district
	{
		get
		{
			return this._district;
		}
		set
		{
			if ((this._district != value))
			{
				this.OndistrictChanging(value);
				this.SendPropertyChanging();
				this._district = value;
				this.SendPropertyChanged("district");
				this.OndistrictChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pincode", DbType="VarChar(50)")]
	public string pincode
	{
		get
		{
			return this._pincode;
		}
		set
		{
			if ((this._pincode != value))
			{
				this.OnpincodeChanging(value);
				this.SendPropertyChanging();
				this._pincode = value;
				this.SendPropertyChanged("pincode");
				this.OnpincodeChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblsegment")]
public partial class tblsegment
{
	
	private System.Nullable<int> _sno_;
	
	private string _segment;
	
	public tblsegment()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[sno.]", Storage="_sno_", DbType="Int")]
	public System.Nullable<int> sno_
	{
		get
		{
			return this._sno_;
		}
		set
		{
			if ((this._sno_ != value))
			{
				this._sno_ = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_segment", DbType="VarChar(50)")]
	public string segment
	{
		get
		{
			return this._segment;
		}
		set
		{
			if ((this._segment != value))
			{
				this._segment = value;
			}
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblteam")]
public partial class tblteam : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _team_id;
	
	private string _name;
	
	private string _team_name;
	
	private string _password;
	
	private string _user_type;
	
	private int _status;
	
	private string _state;
	
	private string _District;
	
	private EntitySet<tbllocation> _tbllocations;
	
	private EntitySet<tbluser> _tblusers;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onteam_idChanging(int value);
    partial void Onteam_idChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void Onteam_nameChanging(string value);
    partial void Onteam_nameChanged();
    partial void OnpasswordChanging(string value);
    partial void OnpasswordChanged();
    partial void Onuser_typeChanging(string value);
    partial void Onuser_typeChanged();
    partial void OnstatusChanging(int value);
    partial void OnstatusChanged();
    partial void OnstateChanging(string value);
    partial void OnstateChanged();
    partial void OnDistrictChanging(string value);
    partial void OnDistrictChanged();
    #endregion
	
	public tblteam()
	{
		this._tbllocations = new EntitySet<tbllocation>(new Action<tbllocation>(this.attach_tbllocations), new Action<tbllocation>(this.detach_tbllocations));
		this._tblusers = new EntitySet<tbluser>(new Action<tbluser>(this.attach_tblusers), new Action<tbluser>(this.detach_tblusers));
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_team_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int team_id
	{
		get
		{
			return this._team_id;
		}
		set
		{
			if ((this._team_id != value))
			{
				this.Onteam_idChanging(value);
				this.SendPropertyChanging();
				this._team_id = value;
				this.SendPropertyChanged("team_id");
				this.Onteam_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(40) NOT NULL", CanBeNull=false)]
	public string name
	{
		get
		{
			return this._name;
		}
		set
		{
			if ((this._name != value))
			{
				this.OnnameChanging(value);
				this.SendPropertyChanging();
				this._name = value;
				this.SendPropertyChanged("name");
				this.OnnameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_team_name", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
	public string team_name
	{
		get
		{
			return this._team_name;
		}
		set
		{
			if ((this._team_name != value))
			{
				this.Onteam_nameChanging(value);
				this.SendPropertyChanging();
				this._team_name = value;
				this.SendPropertyChanged("team_name");
				this.Onteam_nameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
	public string password
	{
		get
		{
			return this._password;
		}
		set
		{
			if ((this._password != value))
			{
				this.OnpasswordChanging(value);
				this.SendPropertyChanging();
				this._password = value;
				this.SendPropertyChanged("password");
				this.OnpasswordChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_type", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
	public string user_type
	{
		get
		{
			return this._user_type;
		}
		set
		{
			if ((this._user_type != value))
			{
				this.Onuser_typeChanging(value);
				this.SendPropertyChanging();
				this._user_type = value;
				this.SendPropertyChanged("user_type");
				this.Onuser_typeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status", DbType="Int NOT NULL")]
	public int status
	{
		get
		{
			return this._status;
		}
		set
		{
			if ((this._status != value))
			{
				this.OnstatusChanging(value);
				this.SendPropertyChanging();
				this._status = value;
				this.SendPropertyChanged("status");
				this.OnstatusChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_state", DbType="NVarChar(50)")]
	public string state
	{
		get
		{
			return this._state;
		}
		set
		{
			if ((this._state != value))
			{
				this.OnstateChanging(value);
				this.SendPropertyChanging();
				this._state = value;
				this.SendPropertyChanged("state");
				this.OnstateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_District", DbType="NVarChar(50)")]
	public string District
	{
		get
		{
			return this._District;
		}
		set
		{
			if ((this._District != value))
			{
				this.OnDistrictChanging(value);
				this.SendPropertyChanging();
				this._District = value;
				this.SendPropertyChanged("District");
				this.OnDistrictChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblteam_tbllocation", Storage="_tbllocations", ThisKey="team_id", OtherKey="team_id")]
	public EntitySet<tbllocation> tbllocations
	{
		get
		{
			return this._tbllocations;
		}
		set
		{
			this._tbllocations.Assign(value);
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblteam_tbluser", Storage="_tblusers", ThisKey="team_id", OtherKey="team_id")]
	public EntitySet<tbluser> tblusers
	{
		get
		{
			return this._tblusers;
		}
		set
		{
			this._tblusers.Assign(value);
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void attach_tbllocations(tbllocation entity)
	{
		this.SendPropertyChanging();
		entity.tblteam = this;
	}
	
	private void detach_tbllocations(tbllocation entity)
	{
		this.SendPropertyChanging();
		entity.tblteam = null;
	}
	
	private void attach_tblusers(tbluser entity)
	{
		this.SendPropertyChanging();
		entity.tblteam = this;
	}
	
	private void detach_tblusers(tbluser entity)
	{
		this.SendPropertyChanging();
		entity.tblteam = null;
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbluser")]
public partial class tbluser : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _user_id;
	
	private int _team_id;
	
	private int _campaign_id;
	
	private System.Nullable<int> _location_id;
	
	private string _user_name;
	
	private string _imei_first;
	
	private string _imei_second;
	
	private System.Nullable<bool> _status;
	
	private System.Nullable<System.DateTime> _createdOn;
	
	private string _state;
	
	private string _District;
	
	private string _MobileNo;
	
	private string _Roles;
	
	private string _Password;
	
	private string _EmailId;
	
	private EntityRef<tblcampaign> _tblcampaign;
	
	private EntityRef<tblteam> _tblteam;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onuser_idChanging(int value);
    partial void Onuser_idChanged();
    partial void Onteam_idChanging(int value);
    partial void Onteam_idChanged();
    partial void Oncampaign_idChanging(int value);
    partial void Oncampaign_idChanged();
    partial void Onlocation_idChanging(System.Nullable<int> value);
    partial void Onlocation_idChanged();
    partial void Onuser_nameChanging(string value);
    partial void Onuser_nameChanged();
    partial void Onimei_firstChanging(string value);
    partial void Onimei_firstChanged();
    partial void Onimei_secondChanging(string value);
    partial void Onimei_secondChanged();
    partial void OnstatusChanging(System.Nullable<bool> value);
    partial void OnstatusChanged();
    partial void OncreatedOnChanging(System.Nullable<System.DateTime> value);
    partial void OncreatedOnChanged();
    partial void OnstateChanging(string value);
    partial void OnstateChanged();
    partial void OnDistrictChanging(string value);
    partial void OnDistrictChanged();
    partial void OnMobileNoChanging(string value);
    partial void OnMobileNoChanged();
    partial void OnRolesChanging(string value);
    partial void OnRolesChanged();
    partial void OnPasswordChanging(string value);
    partial void OnPasswordChanged();
    partial void OnEmailIdChanging(string value);
    partial void OnEmailIdChanged();
    #endregion
	
	public tbluser()
	{
		this._tblcampaign = default(EntityRef<tblcampaign>);
		this._tblteam = default(EntityRef<tblteam>);
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int user_id
	{
		get
		{
			return this._user_id;
		}
		set
		{
			if ((this._user_id != value))
			{
				this.Onuser_idChanging(value);
				this.SendPropertyChanging();
				this._user_id = value;
				this.SendPropertyChanged("user_id");
				this.Onuser_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_team_id", DbType="Int NOT NULL")]
	public int team_id
	{
		get
		{
			return this._team_id;
		}
		set
		{
			if ((this._team_id != value))
			{
				if (this._tblteam.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.Onteam_idChanging(value);
				this.SendPropertyChanging();
				this._team_id = value;
				this.SendPropertyChanged("team_id");
				this.Onteam_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_campaign_id", DbType="Int NOT NULL")]
	public int campaign_id
	{
		get
		{
			return this._campaign_id;
		}
		set
		{
			if ((this._campaign_id != value))
			{
				if (this._tblcampaign.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.Oncampaign_idChanging(value);
				this.SendPropertyChanging();
				this._campaign_id = value;
				this.SendPropertyChanged("campaign_id");
				this.Oncampaign_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_location_id", DbType="Int")]
	public System.Nullable<int> location_id
	{
		get
		{
			return this._location_id;
		}
		set
		{
			if ((this._location_id != value))
			{
				this.Onlocation_idChanging(value);
				this.SendPropertyChanging();
				this._location_id = value;
				this.SendPropertyChanged("location_id");
				this.Onlocation_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_name", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
	public string user_name
	{
		get
		{
			return this._user_name;
		}
		set
		{
			if ((this._user_name != value))
			{
				this.Onuser_nameChanging(value);
				this.SendPropertyChanging();
				this._user_name = value;
				this.SendPropertyChanged("user_name");
				this.Onuser_nameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_imei_first", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
	public string imei_first
	{
		get
		{
			return this._imei_first;
		}
		set
		{
			if ((this._imei_first != value))
			{
				this.Onimei_firstChanging(value);
				this.SendPropertyChanging();
				this._imei_first = value;
				this.SendPropertyChanged("imei_first");
				this.Onimei_firstChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_imei_second", DbType="NVarChar(50)")]
	public string imei_second
	{
		get
		{
			return this._imei_second;
		}
		set
		{
			if ((this._imei_second != value))
			{
				this.Onimei_secondChanging(value);
				this.SendPropertyChanging();
				this._imei_second = value;
				this.SendPropertyChanged("imei_second");
				this.Onimei_secondChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status", DbType="Bit")]
	public System.Nullable<bool> status
	{
		get
		{
			return this._status;
		}
		set
		{
			if ((this._status != value))
			{
				this.OnstatusChanging(value);
				this.SendPropertyChanging();
				this._status = value;
				this.SendPropertyChanged("status");
				this.OnstatusChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_createdOn", DbType="DateTime")]
	public System.Nullable<System.DateTime> createdOn
	{
		get
		{
			return this._createdOn;
		}
		set
		{
			if ((this._createdOn != value))
			{
				this.OncreatedOnChanging(value);
				this.SendPropertyChanging();
				this._createdOn = value;
				this.SendPropertyChanged("createdOn");
				this.OncreatedOnChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_state", DbType="NVarChar(50)")]
	public string state
	{
		get
		{
			return this._state;
		}
		set
		{
			if ((this._state != value))
			{
				this.OnstateChanging(value);
				this.SendPropertyChanging();
				this._state = value;
				this.SendPropertyChanged("state");
				this.OnstateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_District", DbType="NVarChar(50)")]
	public string District
	{
		get
		{
			return this._District;
		}
		set
		{
			if ((this._District != value))
			{
				this.OnDistrictChanging(value);
				this.SendPropertyChanging();
				this._District = value;
				this.SendPropertyChanged("District");
				this.OnDistrictChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MobileNo", DbType="NVarChar(15)")]
	public string MobileNo
	{
		get
		{
			return this._MobileNo;
		}
		set
		{
			if ((this._MobileNo != value))
			{
				this.OnMobileNoChanging(value);
				this.SendPropertyChanging();
				this._MobileNo = value;
				this.SendPropertyChanged("MobileNo");
				this.OnMobileNoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Roles", DbType="NVarChar(30)")]
	public string Roles
	{
		get
		{
			return this._Roles;
		}
		set
		{
			if ((this._Roles != value))
			{
				this.OnRolesChanging(value);
				this.SendPropertyChanging();
				this._Roles = value;
				this.SendPropertyChanged("Roles");
				this.OnRolesChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="NVarChar(15)")]
	public string Password
	{
		get
		{
			return this._Password;
		}
		set
		{
			if ((this._Password != value))
			{
				this.OnPasswordChanging(value);
				this.SendPropertyChanging();
				this._Password = value;
				this.SendPropertyChanged("Password");
				this.OnPasswordChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmailId", DbType="NVarChar(100)")]
	public string EmailId
	{
		get
		{
			return this._EmailId;
		}
		set
		{
			if ((this._EmailId != value))
			{
				this.OnEmailIdChanging(value);
				this.SendPropertyChanging();
				this._EmailId = value;
				this.SendPropertyChanged("EmailId");
				this.OnEmailIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblcampaign_tbluser", Storage="_tblcampaign", ThisKey="campaign_id", OtherKey="campaign_id", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
	public tblcampaign tblcampaign
	{
		get
		{
			return this._tblcampaign.Entity;
		}
		set
		{
			tblcampaign previousValue = this._tblcampaign.Entity;
			if (((previousValue != value) 
						|| (this._tblcampaign.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._tblcampaign.Entity = null;
					previousValue.tblusers.Remove(this);
				}
				this._tblcampaign.Entity = value;
				if ((value != null))
				{
					value.tblusers.Add(this);
					this._campaign_id = value.campaign_id;
				}
				else
				{
					this._campaign_id = default(int);
				}
				this.SendPropertyChanged("tblcampaign");
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblteam_tbluser", Storage="_tblteam", ThisKey="team_id", OtherKey="team_id", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
	public tblteam tblteam
	{
		get
		{
			return this._tblteam.Entity;
		}
		set
		{
			tblteam previousValue = this._tblteam.Entity;
			if (((previousValue != value) 
						|| (this._tblteam.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._tblteam.Entity = null;
					previousValue.tblusers.Remove(this);
				}
				this._tblteam.Entity = value;
				if ((value != null))
				{
					value.tblusers.Add(this);
					this._team_id = value.team_id;
				}
				else
				{
					this._team_id = default(int);
				}
				this.SendPropertyChanged("tblteam");
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblUserSegment")]
public partial class tblUserSegment : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _Id;
	
	private System.Nullable<int> _UserId;
	
	private string _Segment;
	
	private System.Nullable<System.DateTime> _CreatedOn;
	
	private System.Nullable<bool> _IsDeleted;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnUserIdChanging(System.Nullable<int> value);
    partial void OnUserIdChanged();
    partial void OnSegmentChanging(string value);
    partial void OnSegmentChanged();
    partial void OnCreatedOnChanging(System.Nullable<System.DateTime> value);
    partial void OnCreatedOnChanged();
    partial void OnIsDeletedChanging(System.Nullable<bool> value);
    partial void OnIsDeletedChanged();
    #endregion
	
	public tblUserSegment()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int Id
	{
		get
		{
			return this._Id;
		}
		set
		{
			if ((this._Id != value))
			{
				this.OnIdChanging(value);
				this.SendPropertyChanging();
				this._Id = value;
				this.SendPropertyChanged("Id");
				this.OnIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserId", DbType="Int")]
	public System.Nullable<int> UserId
	{
		get
		{
			return this._UserId;
		}
		set
		{
			if ((this._UserId != value))
			{
				this.OnUserIdChanging(value);
				this.SendPropertyChanging();
				this._UserId = value;
				this.SendPropertyChanged("UserId");
				this.OnUserIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Segment", DbType="NVarChar(50)")]
	public string Segment
	{
		get
		{
			return this._Segment;
		}
		set
		{
			if ((this._Segment != value))
			{
				this.OnSegmentChanging(value);
				this.SendPropertyChanging();
				this._Segment = value;
				this.SendPropertyChanged("Segment");
				this.OnSegmentChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedOn", DbType="DateTime")]
	public System.Nullable<System.DateTime> CreatedOn
	{
		get
		{
			return this._CreatedOn;
		}
		set
		{
			if ((this._CreatedOn != value))
			{
				this.OnCreatedOnChanging(value);
				this.SendPropertyChanging();
				this._CreatedOn = value;
				this.SendPropertyChanged("CreatedOn");
				this.OnCreatedOnChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsDeleted", DbType="Bit")]
	public System.Nullable<bool> IsDeleted
	{
		get
		{
			return this._IsDeleted;
		}
		set
		{
			if ((this._IsDeleted != value))
			{
				this.OnIsDeletedChanging(value);
				this.SendPropertyChanging();
				this._IsDeleted = value;
				this.SendPropertyChanged("IsDeleted");
				this.OnIsDeletedChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblUserState")]
public partial class tblUserState : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _Id;
	
	private System.Nullable<int> _UserId;
	
	private string _State;
	
	private System.Nullable<System.DateTime> _CreatedOn;
	
	private System.Nullable<bool> _IsDeleted;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnUserIdChanging(System.Nullable<int> value);
    partial void OnUserIdChanged();
    partial void OnStateChanging(string value);
    partial void OnStateChanged();
    partial void OnCreatedOnChanging(System.Nullable<System.DateTime> value);
    partial void OnCreatedOnChanged();
    partial void OnIsDeletedChanging(System.Nullable<bool> value);
    partial void OnIsDeletedChanged();
    #endregion
	
	public tblUserState()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int Id
	{
		get
		{
			return this._Id;
		}
		set
		{
			if ((this._Id != value))
			{
				this.OnIdChanging(value);
				this.SendPropertyChanging();
				this._Id = value;
				this.SendPropertyChanged("Id");
				this.OnIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserId", DbType="Int")]
	public System.Nullable<int> UserId
	{
		get
		{
			return this._UserId;
		}
		set
		{
			if ((this._UserId != value))
			{
				this.OnUserIdChanging(value);
				this.SendPropertyChanging();
				this._UserId = value;
				this.SendPropertyChanged("UserId");
				this.OnUserIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_State", DbType="NVarChar(50)")]
	public string State
	{
		get
		{
			return this._State;
		}
		set
		{
			if ((this._State != value))
			{
				this.OnStateChanging(value);
				this.SendPropertyChanging();
				this._State = value;
				this.SendPropertyChanged("State");
				this.OnStateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedOn", DbType="DateTime")]
	public System.Nullable<System.DateTime> CreatedOn
	{
		get
		{
			return this._CreatedOn;
		}
		set
		{
			if ((this._CreatedOn != value))
			{
				this.OnCreatedOnChanging(value);
				this.SendPropertyChanging();
				this._CreatedOn = value;
				this.SendPropertyChanged("CreatedOn");
				this.OnCreatedOnChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsDeleted", DbType="Bit")]
	public System.Nullable<bool> IsDeleted
	{
		get
		{
			return this._IsDeleted;
		}
		set
		{
			if ((this._IsDeleted != value))
			{
				this.OnIsDeletedChanging(value);
				this.SendPropertyChanging();
				this._IsDeleted = value;
				this.SendPropertyChanged("IsDeleted");
				this.OnIsDeletedChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblworkshops")]
public partial class tblworkshop
{
	
	private System.Nullable<int> _sno_;
	
	private string _workshop;
	
	public tblworkshop()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[sno.]", Storage="_sno_", DbType="Int")]
	public System.Nullable<int> sno_
	{
		get
		{
			return this._sno_;
		}
		set
		{
			if ((this._sno_ != value))
			{
				this._sno_ = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_workshop", DbType="VarChar(50)")]
	public string workshop
	{
		get
		{
			return this._workshop;
		}
		set
		{
			if ((this._workshop != value))
			{
				this._workshop = value;
			}
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tempLoc")]
public partial class tempLoc
{
	
	private string _Name;
	
	private string _Latitude;
	
	private string _Longitude;
	
	private string _Description;
	
	public tempLoc()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(100)")]
	public string Name
	{
		get
		{
			return this._Name;
		}
		set
		{
			if ((this._Name != value))
			{
				this._Name = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Latitude", DbType="NVarChar(100)")]
	public string Latitude
	{
		get
		{
			return this._Latitude;
		}
		set
		{
			if ((this._Latitude != value))
			{
				this._Latitude = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Longitude", DbType="NVarChar(100)")]
	public string Longitude
	{
		get
		{
			return this._Longitude;
		}
		set
		{
			if ((this._Longitude != value))
			{
				this._Longitude = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="NVarChar(100)")]
	public string Description
	{
		get
		{
			return this._Description;
		}
		set
		{
			if ((this._Description != value))
			{
				this._Description = value;
			}
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblOTPStatus")]
public partial class tblOTPStatus : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _Id;
	
	private string _TagId;
	
	private string _MobileNumber;
	
	private string _Message;
	
	private System.Nullable<System.DateTime> _CreatedOn;
	
	private System.Nullable<bool> _Isdeleted;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnTagIdChanging(string value);
    partial void OnTagIdChanged();
    partial void OnMobileNumberChanging(string value);
    partial void OnMobileNumberChanged();
    partial void OnMessageChanging(string value);
    partial void OnMessageChanged();
    partial void OnCreatedOnChanging(System.Nullable<System.DateTime> value);
    partial void OnCreatedOnChanged();
    partial void OnIsdeletedChanging(System.Nullable<bool> value);
    partial void OnIsdeletedChanged();
    #endregion
	
	public tblOTPStatus()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int Id
	{
		get
		{
			return this._Id;
		}
		set
		{
			if ((this._Id != value))
			{
				this.OnIdChanging(value);
				this.SendPropertyChanging();
				this._Id = value;
				this.SendPropertyChanged("Id");
				this.OnIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TagId", DbType="NVarChar(50)")]
	public string TagId
	{
		get
		{
			return this._TagId;
		}
		set
		{
			if ((this._TagId != value))
			{
				this.OnTagIdChanging(value);
				this.SendPropertyChanging();
				this._TagId = value;
				this.SendPropertyChanged("TagId");
				this.OnTagIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MobileNumber", DbType="NVarChar(50)")]
	public string MobileNumber
	{
		get
		{
			return this._MobileNumber;
		}
		set
		{
			if ((this._MobileNumber != value))
			{
				this.OnMobileNumberChanging(value);
				this.SendPropertyChanging();
				this._MobileNumber = value;
				this.SendPropertyChanged("MobileNumber");
				this.OnMobileNumberChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Message", DbType="NVarChar(MAX)")]
	public string Message
	{
		get
		{
			return this._Message;
		}
		set
		{
			if ((this._Message != value))
			{
				this.OnMessageChanging(value);
				this.SendPropertyChanging();
				this._Message = value;
				this.SendPropertyChanged("Message");
				this.OnMessageChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedOn", DbType="DateTime")]
	public System.Nullable<System.DateTime> CreatedOn
	{
		get
		{
			return this._CreatedOn;
		}
		set
		{
			if ((this._CreatedOn != value))
			{
				this.OnCreatedOnChanging(value);
				this.SendPropertyChanging();
				this._CreatedOn = value;
				this.SendPropertyChanged("CreatedOn");
				this.OnCreatedOnChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Isdeleted", DbType="Bit")]
	public System.Nullable<bool> Isdeleted
	{
		get
		{
			return this._Isdeleted;
		}
		set
		{
			if ((this._Isdeleted != value))
			{
				this.OnIsdeletedChanging(value);
				this.SendPropertyChanging();
				this._Isdeleted = value;
				this.SendPropertyChanged("Isdeleted");
				this.OnIsdeletedChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblvalvoline_detail")]
public partial class tblvalvoline_detail : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private long _id;
	
	private string _name_of_person;
	
	private string _name_of_outlet;
	
	private System.Nullable<long> _contact_number;
	
	private string _image_url;
	
	private System.Nullable<int> _pincode;
	
	private System.Nullable<long> _adhar_number;
	
	private string _workshop;
	
	private string _segment;
	
	private System.Nullable<long> _counter_potential;
	
	private System.Nullable<long> _no_of_services;
	
	private System.Nullable<long> _valvoline_usage;
	
	private string _preferred_retailer;
	
	private string _remarks;
	
	private string _street_location;
	
	private string _state;
	
	private string _city;
	
	private string _district;
	
	private System.Nullable<int> _campaign_id;
	
	private string _team_name;
	
	private string _lat;
	
	private string _log;
	
	private string _otp_password;
	
	private System.Nullable<bool> _otp_verification;
	
	private System.Nullable<bool> _mob_verify_status;
	
	private string _organization_source;
	
	private string _authenticated_contact;
	
	private string _authenticated_by;
	
	private string _near_by_location;
	
	private string _record_input_form;
	
	private System.Nullable<System.DateTime> _createdOn;
	
	private string _imei_no;
	
	private System.Nullable<bool> _deleted_on;
	
	private System.Nullable<bool> _is_verfy;
	
	private System.Nullable<int> _update_count;
	
	private string _source_of_contact;
	
	private string _date_of_birth;
	
	private string _UserId;
	
	private System.Nullable<System.DateTime> _UpdateOn;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(long value);
    partial void OnidChanged();
    partial void Onname_of_personChanging(string value);
    partial void Onname_of_personChanged();
    partial void Onname_of_outletChanging(string value);
    partial void Onname_of_outletChanged();
    partial void Oncontact_numberChanging(System.Nullable<long> value);
    partial void Oncontact_numberChanged();
    partial void Onimage_urlChanging(string value);
    partial void Onimage_urlChanged();
    partial void OnpincodeChanging(System.Nullable<int> value);
    partial void OnpincodeChanged();
    partial void Onadhar_numberChanging(System.Nullable<long> value);
    partial void Onadhar_numberChanged();
    partial void OnworkshopChanging(string value);
    partial void OnworkshopChanged();
    partial void OnsegmentChanging(string value);
    partial void OnsegmentChanged();
    partial void Oncounter_potentialChanging(System.Nullable<long> value);
    partial void Oncounter_potentialChanged();
    partial void Onno_of_servicesChanging(System.Nullable<long> value);
    partial void Onno_of_servicesChanged();
    partial void Onvalvoline_usageChanging(System.Nullable<long> value);
    partial void Onvalvoline_usageChanged();
    partial void Onpreferred_retailerChanging(string value);
    partial void Onpreferred_retailerChanged();
    partial void OnremarksChanging(string value);
    partial void OnremarksChanged();
    partial void Onstreet_locationChanging(string value);
    partial void Onstreet_locationChanged();
    partial void OnstateChanging(string value);
    partial void OnstateChanged();
    partial void OncityChanging(string value);
    partial void OncityChanged();
    partial void OndistrictChanging(string value);
    partial void OndistrictChanged();
    partial void Oncampaign_idChanging(System.Nullable<int> value);
    partial void Oncampaign_idChanged();
    partial void Onteam_nameChanging(string value);
    partial void Onteam_nameChanged();
    partial void OnlatChanging(string value);
    partial void OnlatChanged();
    partial void OnlogChanging(string value);
    partial void OnlogChanged();
    partial void Onotp_passwordChanging(string value);
    partial void Onotp_passwordChanged();
    partial void Onotp_verificationChanging(System.Nullable<bool> value);
    partial void Onotp_verificationChanged();
    partial void Onmob_verify_statusChanging(System.Nullable<bool> value);
    partial void Onmob_verify_statusChanged();
    partial void Onorganization_sourceChanging(string value);
    partial void Onorganization_sourceChanged();
    partial void Onauthenticated_contactChanging(string value);
    partial void Onauthenticated_contactChanged();
    partial void Onauthenticated_byChanging(string value);
    partial void Onauthenticated_byChanged();
    partial void Onnear_by_locationChanging(string value);
    partial void Onnear_by_locationChanged();
    partial void Onrecord_input_formChanging(string value);
    partial void Onrecord_input_formChanged();
    partial void OncreatedOnChanging(System.Nullable<System.DateTime> value);
    partial void OncreatedOnChanged();
    partial void Onimei_noChanging(string value);
    partial void Onimei_noChanged();
    partial void Ondeleted_onChanging(System.Nullable<bool> value);
    partial void Ondeleted_onChanged();
    partial void Onis_verfyChanging(System.Nullable<bool> value);
    partial void Onis_verfyChanged();
    partial void Onupdate_countChanging(System.Nullable<int> value);
    partial void Onupdate_countChanged();
    partial void Onsource_of_contactChanging(string value);
    partial void Onsource_of_contactChanged();
    partial void Ondate_of_birthChanging(string value);
    partial void Ondate_of_birthChanged();
    partial void OnUserIdChanging(string value);
    partial void OnUserIdChanged();
    partial void OnUpdateOnChanging(System.Nullable<System.DateTime> value);
    partial void OnUpdateOnChanged();
    #endregion
	
	public tblvalvoline_detail()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public long id
	{
		get
		{
			return this._id;
		}
		set
		{
			if ((this._id != value))
			{
				this.OnidChanging(value);
				this.SendPropertyChanging();
				this._id = value;
				this.SendPropertyChanged("id");
				this.OnidChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name_of_person", DbType="VarChar(100)")]
	public string name_of_person
	{
		get
		{
			return this._name_of_person;
		}
		set
		{
			if ((this._name_of_person != value))
			{
				this.Onname_of_personChanging(value);
				this.SendPropertyChanging();
				this._name_of_person = value;
				this.SendPropertyChanged("name_of_person");
				this.Onname_of_personChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name_of_outlet", DbType="VarChar(100)")]
	public string name_of_outlet
	{
		get
		{
			return this._name_of_outlet;
		}
		set
		{
			if ((this._name_of_outlet != value))
			{
				this.Onname_of_outletChanging(value);
				this.SendPropertyChanging();
				this._name_of_outlet = value;
				this.SendPropertyChanged("name_of_outlet");
				this.Onname_of_outletChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_contact_number", DbType="BigInt")]
	public System.Nullable<long> contact_number
	{
		get
		{
			return this._contact_number;
		}
		set
		{
			if ((this._contact_number != value))
			{
				this.Oncontact_numberChanging(value);
				this.SendPropertyChanging();
				this._contact_number = value;
				this.SendPropertyChanged("contact_number");
				this.Oncontact_numberChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_image_url", DbType="VarChar(300)")]
	public string image_url
	{
		get
		{
			return this._image_url;
		}
		set
		{
			if ((this._image_url != value))
			{
				this.Onimage_urlChanging(value);
				this.SendPropertyChanging();
				this._image_url = value;
				this.SendPropertyChanged("image_url");
				this.Onimage_urlChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pincode", DbType="Int")]
	public System.Nullable<int> pincode
	{
		get
		{
			return this._pincode;
		}
		set
		{
			if ((this._pincode != value))
			{
				this.OnpincodeChanging(value);
				this.SendPropertyChanging();
				this._pincode = value;
				this.SendPropertyChanged("pincode");
				this.OnpincodeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_adhar_number", DbType="BigInt")]
	public System.Nullable<long> adhar_number
	{
		get
		{
			return this._adhar_number;
		}
		set
		{
			if ((this._adhar_number != value))
			{
				this.Onadhar_numberChanging(value);
				this.SendPropertyChanging();
				this._adhar_number = value;
				this.SendPropertyChanged("adhar_number");
				this.Onadhar_numberChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_workshop", DbType="VarChar(50)")]
	public string workshop
	{
		get
		{
			return this._workshop;
		}
		set
		{
			if ((this._workshop != value))
			{
				this.OnworkshopChanging(value);
				this.SendPropertyChanging();
				this._workshop = value;
				this.SendPropertyChanged("workshop");
				this.OnworkshopChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_segment", DbType="VarChar(50)")]
	public string segment
	{
		get
		{
			return this._segment;
		}
		set
		{
			if ((this._segment != value))
			{
				this.OnsegmentChanging(value);
				this.SendPropertyChanging();
				this._segment = value;
				this.SendPropertyChanged("segment");
				this.OnsegmentChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_counter_potential", DbType="BigInt")]
	public System.Nullable<long> counter_potential
	{
		get
		{
			return this._counter_potential;
		}
		set
		{
			if ((this._counter_potential != value))
			{
				this.Oncounter_potentialChanging(value);
				this.SendPropertyChanging();
				this._counter_potential = value;
				this.SendPropertyChanged("counter_potential");
				this.Oncounter_potentialChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_no_of_services", DbType="BigInt")]
	public System.Nullable<long> no_of_services
	{
		get
		{
			return this._no_of_services;
		}
		set
		{
			if ((this._no_of_services != value))
			{
				this.Onno_of_servicesChanging(value);
				this.SendPropertyChanging();
				this._no_of_services = value;
				this.SendPropertyChanged("no_of_services");
				this.Onno_of_servicesChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_valvoline_usage", DbType="BigInt")]
	public System.Nullable<long> valvoline_usage
	{
		get
		{
			return this._valvoline_usage;
		}
		set
		{
			if ((this._valvoline_usage != value))
			{
				this.Onvalvoline_usageChanging(value);
				this.SendPropertyChanging();
				this._valvoline_usage = value;
				this.SendPropertyChanged("valvoline_usage");
				this.Onvalvoline_usageChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_preferred_retailer", DbType="VarChar(100)")]
	public string preferred_retailer
	{
		get
		{
			return this._preferred_retailer;
		}
		set
		{
			if ((this._preferred_retailer != value))
			{
				this.Onpreferred_retailerChanging(value);
				this.SendPropertyChanging();
				this._preferred_retailer = value;
				this.SendPropertyChanged("preferred_retailer");
				this.Onpreferred_retailerChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_remarks", DbType="VarChar(300)")]
	public string remarks
	{
		get
		{
			return this._remarks;
		}
		set
		{
			if ((this._remarks != value))
			{
				this.OnremarksChanging(value);
				this.SendPropertyChanging();
				this._remarks = value;
				this.SendPropertyChanged("remarks");
				this.OnremarksChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_street_location", DbType="VarChar(100)")]
	public string street_location
	{
		get
		{
			return this._street_location;
		}
		set
		{
			if ((this._street_location != value))
			{
				this.Onstreet_locationChanging(value);
				this.SendPropertyChanging();
				this._street_location = value;
				this.SendPropertyChanged("street_location");
				this.Onstreet_locationChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_state", DbType="VarChar(50)")]
	public string state
	{
		get
		{
			return this._state;
		}
		set
		{
			if ((this._state != value))
			{
				this.OnstateChanging(value);
				this.SendPropertyChanging();
				this._state = value;
				this.SendPropertyChanged("state");
				this.OnstateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_city", DbType="VarChar(50)")]
	public string city
	{
		get
		{
			return this._city;
		}
		set
		{
			if ((this._city != value))
			{
				this.OncityChanging(value);
				this.SendPropertyChanging();
				this._city = value;
				this.SendPropertyChanged("city");
				this.OncityChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_district", DbType="VarChar(50)")]
	public string district
	{
		get
		{
			return this._district;
		}
		set
		{
			if ((this._district != value))
			{
				this.OndistrictChanging(value);
				this.SendPropertyChanging();
				this._district = value;
				this.SendPropertyChanged("district");
				this.OndistrictChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_campaign_id", DbType="Int")]
	public System.Nullable<int> campaign_id
	{
		get
		{
			return this._campaign_id;
		}
		set
		{
			if ((this._campaign_id != value))
			{
				this.Oncampaign_idChanging(value);
				this.SendPropertyChanging();
				this._campaign_id = value;
				this.SendPropertyChanged("campaign_id");
				this.Oncampaign_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_team_name", DbType="VarChar(50)")]
	public string team_name
	{
		get
		{
			return this._team_name;
		}
		set
		{
			if ((this._team_name != value))
			{
				this.Onteam_nameChanging(value);
				this.SendPropertyChanging();
				this._team_name = value;
				this.SendPropertyChanged("team_name");
				this.Onteam_nameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lat", DbType="VarChar(50)")]
	public string lat
	{
		get
		{
			return this._lat;
		}
		set
		{
			if ((this._lat != value))
			{
				this.OnlatChanging(value);
				this.SendPropertyChanging();
				this._lat = value;
				this.SendPropertyChanged("lat");
				this.OnlatChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[log]", Storage="_log", DbType="VarChar(50)")]
	public string log
	{
		get
		{
			return this._log;
		}
		set
		{
			if ((this._log != value))
			{
				this.OnlogChanging(value);
				this.SendPropertyChanging();
				this._log = value;
				this.SendPropertyChanged("log");
				this.OnlogChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_otp_password", DbType="VarChar(10)")]
	public string otp_password
	{
		get
		{
			return this._otp_password;
		}
		set
		{
			if ((this._otp_password != value))
			{
				this.Onotp_passwordChanging(value);
				this.SendPropertyChanging();
				this._otp_password = value;
				this.SendPropertyChanged("otp_password");
				this.Onotp_passwordChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_otp_verification", DbType="Bit")]
	public System.Nullable<bool> otp_verification
	{
		get
		{
			return this._otp_verification;
		}
		set
		{
			if ((this._otp_verification != value))
			{
				this.Onotp_verificationChanging(value);
				this.SendPropertyChanging();
				this._otp_verification = value;
				this.SendPropertyChanged("otp_verification");
				this.Onotp_verificationChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mob_verify_status", DbType="Bit")]
	public System.Nullable<bool> mob_verify_status
	{
		get
		{
			return this._mob_verify_status;
		}
		set
		{
			if ((this._mob_verify_status != value))
			{
				this.Onmob_verify_statusChanging(value);
				this.SendPropertyChanging();
				this._mob_verify_status = value;
				this.SendPropertyChanged("mob_verify_status");
				this.Onmob_verify_statusChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_organization_source", DbType="VarChar(50)")]
	public string organization_source
	{
		get
		{
			return this._organization_source;
		}
		set
		{
			if ((this._organization_source != value))
			{
				this.Onorganization_sourceChanging(value);
				this.SendPropertyChanging();
				this._organization_source = value;
				this.SendPropertyChanged("organization_source");
				this.Onorganization_sourceChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_authenticated_contact", DbType="VarChar(50)")]
	public string authenticated_contact
	{
		get
		{
			return this._authenticated_contact;
		}
		set
		{
			if ((this._authenticated_contact != value))
			{
				this.Onauthenticated_contactChanging(value);
				this.SendPropertyChanging();
				this._authenticated_contact = value;
				this.SendPropertyChanged("authenticated_contact");
				this.Onauthenticated_contactChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_authenticated_by", DbType="VarChar(50)")]
	public string authenticated_by
	{
		get
		{
			return this._authenticated_by;
		}
		set
		{
			if ((this._authenticated_by != value))
			{
				this.Onauthenticated_byChanging(value);
				this.SendPropertyChanging();
				this._authenticated_by = value;
				this.SendPropertyChanged("authenticated_by");
				this.Onauthenticated_byChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_near_by_location", DbType="VarChar(100)")]
	public string near_by_location
	{
		get
		{
			return this._near_by_location;
		}
		set
		{
			if ((this._near_by_location != value))
			{
				this.Onnear_by_locationChanging(value);
				this.SendPropertyChanging();
				this._near_by_location = value;
				this.SendPropertyChanged("near_by_location");
				this.Onnear_by_locationChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_record_input_form", DbType="VarChar(MAX)")]
	public string record_input_form
	{
		get
		{
			return this._record_input_form;
		}
		set
		{
			if ((this._record_input_form != value))
			{
				this.Onrecord_input_formChanging(value);
				this.SendPropertyChanging();
				this._record_input_form = value;
				this.SendPropertyChanged("record_input_form");
				this.Onrecord_input_formChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_createdOn", DbType="DateTime")]
	public System.Nullable<System.DateTime> createdOn
	{
		get
		{
			return this._createdOn;
		}
		set
		{
			if ((this._createdOn != value))
			{
				this.OncreatedOnChanging(value);
				this.SendPropertyChanging();
				this._createdOn = value;
				this.SendPropertyChanged("createdOn");
				this.OncreatedOnChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_imei_no", DbType="NVarChar(50)")]
	public string imei_no
	{
		get
		{
			return this._imei_no;
		}
		set
		{
			if ((this._imei_no != value))
			{
				this.Onimei_noChanging(value);
				this.SendPropertyChanging();
				this._imei_no = value;
				this.SendPropertyChanged("imei_no");
				this.Onimei_noChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_deleted_on", DbType="Bit")]
	public System.Nullable<bool> deleted_on
	{
		get
		{
			return this._deleted_on;
		}
		set
		{
			if ((this._deleted_on != value))
			{
				this.Ondeleted_onChanging(value);
				this.SendPropertyChanging();
				this._deleted_on = value;
				this.SendPropertyChanged("deleted_on");
				this.Ondeleted_onChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_verfy", DbType="Bit")]
	public System.Nullable<bool> is_verfy
	{
		get
		{
			return this._is_verfy;
		}
		set
		{
			if ((this._is_verfy != value))
			{
				this.Onis_verfyChanging(value);
				this.SendPropertyChanging();
				this._is_verfy = value;
				this.SendPropertyChanged("is_verfy");
				this.Onis_verfyChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_update_count", DbType="Int")]
	public System.Nullable<int> update_count
	{
		get
		{
			return this._update_count;
		}
		set
		{
			if ((this._update_count != value))
			{
				this.Onupdate_countChanging(value);
				this.SendPropertyChanging();
				this._update_count = value;
				this.SendPropertyChanged("update_count");
				this.Onupdate_countChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_source_of_contact", DbType="VarChar(50)")]
	public string source_of_contact
	{
		get
		{
			return this._source_of_contact;
		}
		set
		{
			if ((this._source_of_contact != value))
			{
				this.Onsource_of_contactChanging(value);
				this.SendPropertyChanging();
				this._source_of_contact = value;
				this.SendPropertyChanged("source_of_contact");
				this.Onsource_of_contactChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_date_of_birth", DbType="VarChar(50)")]
	public string date_of_birth
	{
		get
		{
			return this._date_of_birth;
		}
		set
		{
			if ((this._date_of_birth != value))
			{
				this.Ondate_of_birthChanging(value);
				this.SendPropertyChanging();
				this._date_of_birth = value;
				this.SendPropertyChanged("date_of_birth");
				this.Ondate_of_birthChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserId", DbType="NVarChar(30)")]
	public string UserId
	{
		get
		{
			return this._UserId;
		}
		set
		{
			if ((this._UserId != value))
			{
				this.OnUserIdChanging(value);
				this.SendPropertyChanging();
				this._UserId = value;
				this.SendPropertyChanged("UserId");
				this.OnUserIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdateOn", DbType="DateTime")]
	public System.Nullable<System.DateTime> UpdateOn
	{
		get
		{
			return this._UpdateOn;
		}
		set
		{
			if ((this._UpdateOn != value))
			{
				this.OnUpdateOnChanging(value);
				this.SendPropertyChanging();
				this._UpdateOn = value;
				this.SendPropertyChanged("UpdateOn");
				this.OnUpdateOnChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}
#pragma warning restore 1591
